baseURL = "www.yogeshsn.com.np"
languageCode = "en-us"
title = "yogeshsn"
theme = "hugo-blog-awesome"
canoifyURLs = true

[menu]
 [[menu.main]]
    identifier = "Posts"
    name = "Posts"
    url = "/posts/"
    weight ="10"

  [[menu.main]]
    identifier = "about"
    name = "About me"
    url = "/about/yogesh"
    weight ="10"

  [[menu.main]]
    identifier = "References"
    name = "References"
    url = "/references/"
    weight ="20"

  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight ="30"
[[params.socialIcons]]

[[params.socialIcons]]
name = "x"
url = "https://x.com/yogesh__sn"

[[params.socialIcons]]
name = "youtube"
url = "https://www.youtube.com/@palpasky6909/videos"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/yogesh-sn🇳🇵-1926b8184" 

[[params.socialIcons]]
name = "instagram"
url = "https://www.instagram.com/livingonnature"

[params]
  goToTop = true
  ShowBreadCrumbs = true
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true


# Add the following lines for photo, image, and footer

[params.author]
  avatar = "ys.png" # Update with the correct path
  intro = "Yogesh Sharma Neupane"
  name = "Yogesh SN"
  description = "Dream, Discipline, and Dedication "
# Display "Posts" in bold with a horizontal line
  
